In [56]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier, export_graphviz, ExtraTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import tree
import pandas as pd
import numpy as np

In [30]:
iris = load_iris()
data1 = pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])

In [32]:
data1

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
145     2.0  
146     2.0  
147     2.0  
148     2.0  
149     2.0  

[150 rows x 5 columns]

In [33]:
data1.target

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: target, Length: 150, dtype: float64

In [34]:
data1.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [37]:
X= data1[["sepal length (cm)","sepal width (cm)","petal length (cm)","petal width (cm)"]]
Y=data1['target']
  
# using the train test split function
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=10) 

In [38]:
dt_entropy= DecisionTreeClassifier(criterion='entropy',max_depth=3, random_state=0)
dt_gini = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=0)
dt_gini.fit(trainX,trainY)
dt_entropy.fit(trainX,trainY)

DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)

In [42]:
dotfile = open("C:\\Users\\rajat.k.srivastava\\Downloads\\dtree2.dot", 'w')
tree.export_graphviz(dt_gini, out_file = dotfile, feature_names = X.columns)
dotfile.close()

In [43]:
export_graphviz(dt_entropy,'C:\\Users\\rajat.k.srivastava\\Downloads\dt_entropy.tree')

In [44]:
export_graphviz(dt_gini,'C:\\Users\\rajat.k.srivastava\\Downloads\dt_entropy.tree')

In [45]:
predY1=dt_entropy.predict(testX)
predY2=dt_gini.predict(testX)

In [46]:
from sklearn.metrics import accuracy_score

print('Model accuracy score with criterion gini index: {0:0.4f}'. format(accuracy_score(testY, predY1)))
print('Model accuracy score with criterion entropy index: {0:0.4f}'. format(accuracy_score(testY, predY2)))

Model accuracy score with criterion gini index: 0.9211
Model accuracy score with criterion entropy index: 0.9211


In [47]:
# print the scores on training and test set

print('Training set score: {:.4f}'.format(dt_gini.score(trainX,trainY)))

print('Test set score: {:.4f}'.format(dt_gini.score(testX, testY)))

Training set score: 0.9821
Test set score: 0.9211


# Confusion matrix


A confusion matrix is a tool for summarizing the performance of a classification algorithm. A confusion matrix will give us a clear picture of classification model performance and the types of errors produced by the model. It gives us a summary of correct and incorrect predictions broken down by each category. The summary is represented in a tabular form.


Four types of outcomes are possible while evaluating a classification model performance. These four outcomes are described below:-


**True Positives (TP)** – True Positives occur when we predict an observation belongs to a certain class and the observation actually belongs to that class.


**True Negatives (TN)** – True Negatives occur when we predict an observation does not belong to a certain class and the observation actually does not belong to that class.


**False Positives (FP)** – False Positives occur when we predict an observation belongs to a    certain class but the observation actually does not belong to that class. This type of error is called **Type I error.**



**False Negatives (FN)** – False Negatives occur when we predict an observation does not belong to a certain class but the observation actually belongs to that class. This is a very serious error and it is called **Type II error.**



These four outcomes are summarized in a confusion matrix given below.


In [48]:
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(testY, predY1)

print('Confusion matrix\n\n', cm)


Confusion matrix

 [[11  0  0]
 [ 0 13  3]
 [ 0  0 11]]


In [49]:
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(testY, predY2)

print('Confusion matrix\n\n', cm)


Confusion matrix

 [[11  0  0]
 [ 0 13  3]
 [ 0  0 11]]


In [50]:
from sklearn.metrics import classification_report

print(classification_report(testY, predY1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.81      0.90        16
           2       0.79      1.00      0.88        11

    accuracy                           0.92        38
   macro avg       0.93      0.94      0.93        38
weighted avg       0.94      0.92      0.92        38



In [52]:
dt_gini.feature_importances_

array([0.        , 0.        , 0.42700946, 0.57299054])

In [55]:
dt_entropy.feature_importances_

array([0.      , 0.      , 0.321408, 0.678592])

![](img/questions-01.png)